name: peer
dependencies:
  - numpy
  - pip:
    - Django==1.11
    - dj-database-url==0.3.0
    - dj-static==0.0.6
    - gunicorn==19.3.0
    - psycopg2==2.6.1
    - static3==0.6.1
    - wsgiref==0.1.2
    - requests>=2.13.0
    - sendgrid>=0.5.0
    - pytz==2013.7
    - djangoajax==2.3.3
    - urllib3
    - django-secure
    - django-sslserver
    - newrelic
