# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date']},
        ),
    ]
